# -*- coding: utf-8 -*-
"""SlockPrice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U7YSiit3R478og03sX1EeXdx6epxLu9r
"""

import yfinance as yf
import streamlit as st

st.write("""# Simple Stock Price App 
Shown are the stock **closing price** and ***volume price*** of Google!""")

# https://towardsdatascience.com/how-to-get-stock-data-using-python-c0de1df17e75
#define the ticker symbol
tickerSymbol = 'GOOGL'
#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)
#get the historical prices for this ticker
tickerDf = tickerData.history(period='1d', start='2010-5-31', end='2020-5-31')
# Open	High	Low	Close	Volume	Dividends	Stock Splits

st.write("""## Closing Price""")
st.line_chart(tickerDf.Close)
st.write("""## Volume Price""")
st.line_chart(tickerDf.Volume)

